config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "homes#index"

  # Health check endpoint for Kubernetes or other orchestrators
  get "/healthz", to: "health#show"

  resources :posts, only: %i[new create index show edit update destroy] do
    member do
      post :track_official_click
    end
    resources :likes, only: %i[create destroy]
  end

  resource :profile, only: %i[show]

  resources :notifications, only: %i[index] do
    post :mark_notifications_as_read, on: :collection
  end

  resource :lookups, only: %i[create]

  resource :ranking, only: %i[show]
end

app/views/shared/_aqua_header.html.erb
<header>
<div class="text-xl flex p-8 justify-between items-center bg-sky-300">
  <div>
  <%= link_to root_path do %>
  <i class="fa-solid fa-house text-2xl"></i>
  <% end %>
  </div>
  <% if current_user %>
  <div class="flex">
    <%#　stimulusでクリックした時に投稿を表示 %>
    <div data-controller="toggle" class="relative">
      <button data-action="click->toggle#toggle" class="text-black cursor-pointer">
        <i class="fa-solid fa-pen text-2xl"></i>
      </button>
      <div data-toggle-target="menu" class="absolute mt-8 w-60 bg-yellow-100 text-black rounded shadow-lg hidden">
        <%= link_to "動物園を投稿する", new_post_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "水族館を投稿する", new_post_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
      </div>
    </div>
  </div>
    <%= link_to notifications_path do %>
      <i class="fa-solid fa-bell text-2xl"></i>
      <% if @unread_notifications_count > 0 %>
        <span class=""><%= @unread_notifications_count %></span>
      <% end %>
    <% end %>
<div data-controller="hamburger" class="relative">
  <!-- ハンバーガーアイコン -->
  <button data-action="click->hamburger#toggle" class="p-2 cursor-pointer">
    <!-- 三本線アイコン -->
    <svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2"
         viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
  </button>
    <div data-hamburger-target="menu" class="absolute mt-2 right-0 w-60 bg-yellow-100 rounded shadow-lg hidden">
      <%= link_to "水族館に行く", posts_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "動物園に行く", posts_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "マイページ", profile_path, class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "ランキング", ranking_path, class: "block px-4 py-2 hover:bg-gray-100" %>
  </div>
</div>

  <% else %>
  <div class="flex space-x-4">
    <div>
      <%= link_to "館員登録", "/users/sign_up" %>
    </div>
    <div>
      <%= link_to "ログイン", new_user_session_path %>
    </div>
  </div>
  <% end %>
</div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, message| %>
  <% css_class = case key.to_sym
    when :notice
      "bg-green-300 border-green-400 text-green-700" # 成功時
    when :alert
      "bg-red-300 border-red-400 text-red-700"       # エラー時
    else
      "bg-gray-100 border-gray-400 text-gray-700"    # その他
    end
  %>

  <div class="text-center border px-4 py-3 rounded-md shadow-md <%= css_class %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class = "bg-neutral-300 p-10">
  <div class="flex flex-col items-center space-y-2">
   <p>Copyright ©2025 - AquaZooBridge</p>
     <div class="flex space-x-8 mt-4 justify-center">
       <%=link_to "https://github.com/Ryu-it/AquaZooBridge" do %>
         <i class="fa-brands fa-github fa-2xl"></i>
       <% end %>
       <%=link_to "https://x.com/Ryu_Runteq" do %>
         <i class="fa-brands fa-square-x-twitter fa-2xl"></i>
       <% end %>
     </div>
  </div>
</footer>

app/views/shared/_normal_header.html.erb
<header>
<div class="text-xl flex p-8 justify-between items-center bg-neutral-300">
  <div>
  <%= link_to root_path do %>
  <i class="fa-solid fa-house text-2xl"></i>
  <% end %>
  </div>
  <% if current_user %>
  <div class="flex space-x-">
    <%#　stimulusでクリックした時に投稿を表示 %>
    <div data-controller="toggle" class="relative">
      <button data-action="click->toggle#toggle" class="text-black cursor-pointer">
        <i class="fa-solid fa-pen text-2xl"></i>
      </button>
      <div data-toggle-target="menu" class="absolute w-60 mt-8 bg-yellow-100 text-black rounded shadow-lg hidden">
        <%= link_to "動物園を投稿する", new_post_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "水族館を投稿する", new_post_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
      </div>
    </div>
  </div>
    <%= link_to notifications_path do %>
      <i class="fa-solid fa-bell text-2xl"></i>
      <% if @unread_notifications_count > 0 %>
        <span class=""><%= @unread_notifications_count %></span>
      <% end %>
    <% end %>
      <%#　stimulusでハンバーカーメニューを表示 %>
    <div data-controller="hamburger" class="relative inline-block">
      <button data-action="click->hamburger#toggle" class="p-2 cursor-pointer">
    <!-- 三本線アイコン -->
    <svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2"
         viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
  </button>
      <%#　ここからメニューをクリックした後の表示 %>
      <div data-hamburger-target="menu" class = "absolute mt-2 right-0 w-40 bg-yellow-100 text-black rounded shadow-lg hidden">
        <%= link_to "水族館に行く", posts_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "動物園に行く", posts_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "マイページ", profile_path, class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "ランキング", ranking_path, class: "block px-4 py-2 hover:bg-gray-100" %>
      </div>
    </div>

  <% else %>
  <div class="flex space-x-4">
    <div>
      <%= link_to "館員登録", "/users/sign_up" %>
    </div>
    <div>
      <%= link_to "ログイン", new_user_session_path %>
    </div>
  </div>
  <% end %>
</div>
</header>

app/views/shared/_zoo_header.html.erb
<header>
<div class="text-xl flex p-8 justify-between items-center bg-amber-700">
  <div>
  <%= link_to root_path do %>
  <i class="fa-solid fa-house text-2xl"></i>
  <% end %>
  </div>
  <% if current_user %>
  <div class="flex">
    <%#　stimulusでクリックした時に投稿を表示 %>
    <div data-controller="toggle" class="relative">
      <button data-action="click->toggle#toggle" class="text-black cursor-pointer">
        <i class="fa-solid fa-pen text-2xl"></i>
      </button>
      <div data-toggle-target="menu" class="absolute mt-8 w-60 bg-yellow-100 text-black rounded shadow-lg hidden">
        <%= link_to "動物園を投稿する", new_post_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
        <%= link_to "水族館を投稿する", new_post_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
      </div>
    </div>
  </div>
    <%= link_to notifications_path do %>
      <i class="fa-solid fa-bell text-2xl"></i>
      <% if @unread_notifications_count > 0 %>
        <span class=""><%= @unread_notifications_count %></span>
      <% end %>
    <% end %>
<div data-controller="hamburger" class="relative">
  <!-- ハンバーガーアイコン -->
  <button data-action="click->hamburger#toggle" class="p-2 cursor-pointer">
    <!-- 三本線アイコン -->
    <svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2"
         viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
  </button>
    <div data-hamburger-target="menu" class="absolute mt-2 right-0 w-60 bg-yellow-100 rounded shadow-lg hidden">
      <%= link_to "水族館に行く", posts_path(category: "aqua"), class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "動物園に行く", posts_path(category: "zoo"), class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "マイページ", profile_path, class: "block px-4 py-2 hover:bg-gray-100" %>
      <%= link_to "ランキング", ranking_path, class: "block px-4 py-2 hover:bg-gray-100" %>
  </div>
</div>

  <% else %>
  <div class="flex space-x-4">
    <div>
      <%= link_to "館員登録", "/users/sign_up" %>
    </div>
    <div>
      <%= link_to "ログイン", new_user_session_path %>
    </div>
  </div>
  <% end %>
</div>
</header>