config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "homes#index"

  # Health check endpoint for Kubernetes or other orchestrators
  get "/healthz", to: "health#show"

  resources :posts, only: %i[new create index show edit update destroy] do
    member do
      post :track_official_click
    end
    resources :likes, only: %i[create destroy]
  end

  resource :profile, only: %i[show]

  resources :notifications, only: %i[index] do
    post :mark_notifications_as_read, on: :collection
  end

  resource :lookups, only: %i[create]

  resource :ranking, only: %i[show]
end

app/models/post.rb
class Post < ApplicationRecord
  # == ActiveStorage ==
  has_one_attached :image

  validates :word, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  belongs_to :user
  belongs_to :category
  belongs_to :area
  belongs_to :facility

  accepts_nested_attributes_for :facility

  validate :image_content_type
  validate :image_size

  before_validation :normalize_facility

  private

  def normalize_facility
    if facility && facility.name.present?
      self.facility = Facility.find_or_create_by(name: facility.name) do |f|
        f.official_url = facility.official_url
      end
    end
  end

  # 特定の画像だけを保存
  def image_content_type
    return unless image.attached?
    allowed = %w[image/jpeg image/jpg image/png]
    unless image.content_type.in?(allowed)
      errors.add(:image, "は JPEG または PNG をアップロードしてください")
    end
  end

  def image_size
    return unless image.attached? && image.blob
    if image.blob.byte_size > 15.megabytes
      errors.add(:image, "は10MB以下にしてください")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[ word body area_id ] # ← 検索対象にしてよいカラムだけを配列で返す
  end

  def self.ransackable_associations(auth_object = nil)
    %w[ area user category facility ]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy track_official_click]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_owner!, only: %i[edit update destroy]
  before_action :check_params_category, only: %i[new edit update index show]

  def index
      @areas = Area.all
      @q = Post.ransack(params[:q])
      scope = @q.result(distinct: true)
                .joins(:category)
                .where(categories: { name: params[:category] })

      @posts = scope
                .select("posts.*").distinct
                .order("posts.created_at DESC, posts.id DESC")
                .page(params[:page]).per(9)
                .preload(:user)

      case params[:category]
      when "zoo"
        render "zoo_index"
      when "aqua"
        render "aqua_index"
      end
  end

  def show
    title = @post.facility&.name.presence || "AquaZooBridge"
    ogimg =
    if @post.image.attached?
      rails_blob_url(@post.image, only_path: false)
    else
      view_context.image_url("AquaZooBridge.png")
    end

    set_meta_tags(
      title: title,
      og: {
        title: title,
        type: "article",
        url: request.original_url,
        image: ogimg,
        description: "#{title}の投稿をチェックしよう！" # 説明文も追加
      },
      twitter: {
        card: "summary_large_image",
        image: ogimg,
        title: title # Twitterカード用のタイトルも明示的に設定
      }
    )

    case params[:category]
    when "zoo"
      render "zoo_show"
    when "aqua"
      render "aqua_show"
    end
  end

  def new
    @post = Post.new
    @post.build_facility
    case params[:category]
    when "zoo"
      render "zoo_new"
    when "aqua"
      render "aqua_new"
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.category = Category.find_by(name: params[:category])

    if @post.save
      flash[:notice] = "投稿に成功しました"

      if @post.category.name == "zoo"
        redirect_to post_path(@post, category: "zoo")
      else
        redirect_to post_path(@post, category: "aqua")
      end

    else
      flash.now[:alert] = "投稿に失敗しました"

      # カテゴリーに応じて render を変える
      if @post.category.name == "zoo"
        render :zoo_new, status: :unprocessable_entity
      else
        render :aqua_new, status: :unprocessable_entity
      end
    end
  end

  def edit
    case params[:category]
    when "zoo"
      render "zoo_edit"
    when "aqua"
      render "aqua_edit"
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "編集に成功しました"

      if @post.category.name == "zoo"
        redirect_to posts_path(category: "zoo")
      else
        redirect_to posts_path(category: "aqua")
      end

    else
      flash.now[:alert] = "編集に失敗しました"

      # カテゴリーに応じて render を変える
      if @post.category.name == "zoo"
        render :zoo_edit, status: :unprocessable_entity
      else
        render :aqua_edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "削除に成功しました"
    redirect_to root_path
  end

  def track_official_click
    @post = Post.find(params[:id])
    CreateNotification.url_visit(visitor: current_user, post: @post)
    head :no_content
  end

  private

  # 自分の投稿だけを見つける
  def set_post
    @post = Post.find(params[:id])
  end

  # 投稿のidと今のユーザーのidを比較して遷移してメッセージ
  def authorize_owner!
    unless @post.user_id == current_user.id
      redirect_to root_path, alert: "権限がありません" and return
    end
  end

  def post_params
    params.require(:post).permit(
    :word,
    :body,
    :area_id,
    :image,
    facility_attributes: [ :name, :official_url ]
    )
  end

  def check_params_category
    unless params[:category].in?(%w[zoo aqua])
      redirect_to root_path, alert: "不正なアクセスです" and return
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_search_form.html.erb
<%= search_form_for q, url: url do |f| %>
<div class="mt-8 flex justify-center gap-6 items-center w-full">
      <div class="">
            <%= f.collection_select :area_id_eq, @areas, :id, :name,
            { include_blank: "エリアを選択" },
            { class: "rounded-md bg-white select select-bordered p-3" } %>
      </div>
      <div class="w-1/2">
            <%= f.search_field :word_or_body_or_facility_name_cont,
            placeholder: "キーワードを入力",
            class: "w-full bg-white border rounded-md shadow-sm p-3 focus:ring-sky-500 focus:border-sky-500" %>
      </div>
      <%= hidden_field_tag :category, params[:category] %>
      <div class="">
      <%= f.submit "検索", class: "rounded-md p-3 w-full bg-sky-500 hover:bg-sky-600 text-white font-bold py-2 rounded-ful" %>
      </div>
<% end %>
</div>

app/views/posts/aqua_edit.html.erb
<%= render "shared/aqua_header" %>
<%= render "shared/flash_message" %>

<div class="flex items-center justify-center min-h-screen bg-sky-900 h-full">
  <%= form_with model: @post, class: "mt-12 w-full max-w-xl space-y-6 px-4 md:space-y-4 md:px-0" do |f| %>
    <div>
      <%= f.fields_for :facility do |facility_fields| %>
        <div data-controller="lookup">
          <div>
            <%= facility_fields.label :name, "水族館の名前", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :name,
                  placeholder: "例：すみだ水族館",
                  class: "bg-sky-300 mt-2 mb-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "name", action: "input->lookup#fetch" } %>
          </div>

          <div>
            <%= facility_fields.label :official_url, "水族館のURL", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :official_url,
                  class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "url" } %>
          </div>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :word, "ひとこと", class: "text-white text-sm md:text-base" %>
      <%= f.text_field :word,
            placeholder: "例：ペンギン！！",
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :body, "ここが好き！", class: "text-white text-sm md:text-base" %>
      <%= f.text_area :body,
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
            rows: "10" %>
    </div>

    <div>
      <%= f.label :area_id, "都道府県", class: "text-white text-sm md:text-base" %>
      <%= f.select :area_id, Area.all.collect { |p| [p.name, p.id] },
            { include_blank: "選択してください" },
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :image, "画像をアップロード", class: "text-white text-sm md:text-base" %>
      <%= f.file_field :image,
            class: "bg-sky-300 mt-2 block w-full border rounded-md p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <%= hidden_field_tag :category, "aqua" %>

    <div>
      <%= f.submit "編集",
            class: "mb-12 block w-full md:w-auto bg-neutral-300 hover:bg-neutral-500 py-3 md:py-2 px-4 rounded-md shadow-md transition duration-300 text-base md:text-lg" %>
    </div>
  <% end %>
</div>

app/views/posts/aqua_index.html.erb
<%= render "shared/aqua_header" %>
<%= render "shared/flash_message" %>
<div class = "flex items-center justify-center h-full bg-sky-900 min-h-screen">
  <div class="max-w-7xl mb-10 mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
    <div class="col-span-full flex justify-center">
      <%= render "search_form", q: @q, url: posts_path(category: "aqua") %>
    </div>
    <% @posts.each do |post| %>
      <div class="h-full card-body bg-sky-300 border rounded-xl shadow-md p-4 flex flex-col justify-between">
<%# 投稿をクリックしたときに詳細のurlに飛ぶように %>
        <div
  data-controller="redirect"
  data-redirect-url-value="<%= post_path(post, category: 'aqua') %>"
  data-action="click->redirect#navigate"
  role="button"
  class="cursor-pointer"
  data-turbo="false">
          <div class= "inline-block p-2 rounded-xl text-white bg-sky-900"> 
            <%= post.user.name %> 
          </div>
          <div class= "text-white p-4 text-xl font-bold text-center mt-4 mb-4 bg-sky-900 rounded-xl"> 
            「 <%= post.word %> 」 
          </div>
          <div class="">
              <% if post.image.attached? %>
                <%= image_tag post.image %>
              <% else %>
                <%= image_tag "fish.png", class: "" %>
              <% end %>
          </div>
        </div>
        <%= render partial: "likes/like_button", locals: { post: post } %>
      </div>
    <% end %>
    <div class="mt-4 col-span-full flex justify-center">
      <%= paginate @posts, window: 1, outer_window: 1 %>
    </div>
  </div>
</div>

app/views/posts/aqua_new.html.erb
<%= render "shared/aqua_header" %>
<%= render "shared/flash_message" %>

<div class="flex items-center justify-center min-h-screen bg-sky-900 h-full">
  <%= form_with model: @post, class: "mt-12 w-full max-w-xl space-y-6 px-4 md:space-y-4 md:px-0" do |f| %>
    <div>
      <%= f.fields_for :facility do |facility_fields| %>
        <div data-controller="lookup">
          <div>
            <%= facility_fields.label :name, "水族館の名前", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :name,
                  placeholder: "例：すみだ水族館",
                  class: "bg-sky-300 mt-2 mb-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "name", action: "input->lookup#fetch" } %>
          </div>

          <div>
            <%= facility_fields.label :official_url, "水族館のURL", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :official_url,
                  class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "url" } %>
          </div>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :image, "画像をアップロード", class: "text-white text-sm md:text-base" %>
      <%= f.file_field :image,
            class: "bg-sky-300 mt-2 block w-full border rounded-md p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :word, "ひとこと", class: "text-white text-sm md:text-base" %>
      <%= f.text_field :word,
            placeholder: "例：ペンギン！！",
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :body, "思い出・ここが好き", class: "text-white text-sm md:text-base" %>
      <%= f.text_area :body,
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
            rows: "10" %>
    </div>

    <div>
      <%= f.label :area_id, "都道府県", class: "text-white text-sm md:text-base" %>
      <%= f.select :area_id, Area.all.collect { |p| [p.name, p.id] },
            { include_blank: "選択してください" },
            class: "bg-sky-300 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <%= hidden_field_tag :category, "aqua" %>

    <div>
      <%= f.submit "投稿",
            class: "mb-12 block w-full md:w-auto bg-neutral-300 hover:bg-neutral-500 py-3 md:py-2 px-4 rounded-md shadow-md transition duration-300 text-base md:text-lg" %>
    </div>
  <% end %>
</div>

app/views/posts/aqua_show.html.erb
<%= render "shared/aqua_header" %>
<div class = "flex items-center justify-center bg-sky-900 min-h-screen">
    <div class="w-full max-w-6xl px-2 my-16">
        <div class="bg-sky-300 border rounded-lg shadow-md p-12">
            <div class="font-bold text-xl">
                <%= @post.user.name %>
            </div>
            <div class="mt-10 mb-4 font-bold text-xl">
                <%= @post.facility.name %> （ <%= @post.area.name %> ）
            </div>
            <div class="">
                <% if @post.image.attached? %>
                    <%= image_tag @post.image %>
                <% else %>
                    <%= image_tag "fish.png", class: "" %>
                <% end %>
            </div>
            <p class = "text-center mt-12 text-xl">「 思い出・ここが好き 」</p> 
            <div class= "mt-10 rounded-lg p-8 border bg-sky-900 text-xl text-white text-center"> 
                <%= @post.body %>  
            </div>
            <p class = "text-center mt-12 text-xl">「 水族館URL 」</p> 
            <div class= "underline mt-10 rounded-lg p-8 border bg-sky-900 text-xl text-white text-center"> 
                <%= link_to @post.facility.official_url,
                            @post.facility.official_url,
                            target: "_blank",
                            rel: "noopener noreferrer",
                            class: "break-all",
                            data: {
                                controller: "click-track",
                                action: "click->click-track#track",     
                                click_track_url_value: track_official_click_post_path(@post)
                            } %> 
            </div>
            <%= render partial: "likes/like_button", locals: { post: @post } %>
        </div>
            <%# 投稿したユーザーだけが編集・投稿できる %>
            <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="flex justify-center items-center mt-8 text-xl text-white space-x-12">
            <%= link_to edit_post_path(category: "aqua"), class: "" do %>
                <i class="fa-solid fa-pen-to-square text-2xl"></i>
            <% end %>
            <%= link_to post_path(@post), method: :delete, data: { turbo_method: :delete }, class: "" do %>
                <i class="fa-solid fa-trash text-2xl"></i>
            <% end %>
        </div>
            <% end %>
        <%# ライン共有ボタン %>
        <div class="line-share-button mt-8 flex justify-center items-center">
            <div class="line-it-button" 
                data-lang="ja" 
                data-type="share-a" 
                data-env="REAL"
                data-url="<%= post_url(@post, category: "zoo") %>" 
                data-text="<%= @post.facility.name %>" 
                data-color="default"
                data-size="large" 
                data-count="true" 
                data-ver="3" 
                style="display: none;">
            </div>
        </div>
                    <%# xのシェア機能 %>
<div class="mt-8 flex justify-center items-center">
   <% share_url = "https://twitter.com/intent/tweet?url=#{CGI.escape(request.original_url)}&text=#{CGI.escape(title)}" %>

<%= link_to share_url, target: "_blank", rel: "noopener noreferrer", class: "bg-sky-500 inline-block text-white px-4 py-2 rounded-lg" do %>
Xでシェア
<% end %>
</div>
    </div>
</div>

app/views/posts/zoo_edit.html.erb
<%= render "shared/zoo_header" %>
<%= render "shared/flash_message" %>

<div class="flex items-center justify-center min-h-screen bg-lime-900 h-full">
  <%= form_with model: @post, class: "mt-12 w-full max-w-xl space-y-6 px-4 md:space-y-4 md:px-0" do |f| %>
    <div>
      <%= f.fields_for :facility do |facility_fields| %>
        <div data-controller="lookup">
          <div>
            <%= facility_fields.label :name, "動物園の名前", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :name,
                  placeholder: "例：東武動物公園",
                  class: "bg-amber-700 mt-2 mb-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "name", action: "input->lookup#fetch" } %>
          </div>

          <div>
            <%= facility_fields.label :official_url, "動物園のURL", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :official_url,
                  class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "url" } %>
          </div>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :word, "ひとこと", class: "text-white text-sm md:text-base" %>
      <%= f.text_field :word,
            placeholder: "例：キリン！！",
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :body, "ここが好き！", class: "text-white text-sm md:text-base" %>
      <%= f.text_area :body,
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
            rows: "10" %>
    </div>

    <div>
      <%= f.label :area_id, "都道府県", class: "text-white text-sm md:text-base" %>
      <%= f.select :area_id, Area.all.collect { |p| [p.name, p.id] },
            { include_blank: "選択してください" },
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :image, "画像をアップロード", class: "text-white text-sm md:text-base" %>
      <%= f.file_field :image,
            class: "bg-amber-700 mt-2 block w-full border rounded-md p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <%= hidden_field_tag :category, "zoo" %>

    <div>
      <%= f.submit "編集",
            class: "mb-12 block w-full md:w-auto bg-neutral-300 hover:bg-neutral-500 py-3 md:py-2 px-4 rounded-md shadow-md transition duration-300 text-base md:text-lg" %>
    </div>
  <% end %>
</div>

app/views/posts/zoo_index.html.erb
<%= render "shared/zoo_header" %>
<%= render "shared/flash_message" %>
<div class = "flex items-center justify-center h-full bg-lime-900 min-h-screen">
  <div class="max-w-7xl mb-10 mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
    <div class="col-span-full flex justify-center">
      <%= render "search_form", q: @q, url: posts_path(category: "zoo") %>
    </div>
    <% @posts.each do |post| %>
      <div class="h-full card-body bg-amber-700 border rounded-xl shadow-md p-4 flex flex-col justify-between">
        <%# 投稿をクリックしたときに詳細のurlに飛ぶように %>
        <div
  data-controller="redirect"
  data-redirect-url-value="<%= post_path(post, category: 'zoo') %>"
  data-action="click->redirect#navigate"
  role="button"
  class="cursor-pointer"
  data-turbo="false">
          <div class= "inline-block p-2 text-center mt-4 mb-4 bg-lime-900 rounded-xl"> 
            <%= post.user.name %> 
          </div>
          <div class= "p-4 text-xl font-bold text-center mt-4 mb-4 bg-lime-900 rounded-xl"> 
            「 <%= post.word %> 」 
          </div>
          <div class="">
            <% if post.image.attached? %>
              <%= image_tag post.image %>
            <% else %>
              <%= image_tag "kirin.png", class: "" %>
            <% end %>
          </div>
        </div>
        <%= render partial: "likes/like_button", locals: { post: post } %>
      </div>
    <% end %>
    <div class="mt-4 col-span-full flex justify-center">
      <%= paginate @posts, window: 1, outer_window: 1 %>
    </div>
  </div>
</div>

app/views/posts/zoo_new.html.erb
<%= render "shared/zoo_header" %>
<%= render "shared/flash_message" %>

<div class="flex items-center justify-center min-h-screen bg-lime-900 h-full">
  <%= form_with model: @post, class: "mt-12 w-full max-w-xl space-y-6 px-4 md:space-y-4 md:px-0" do |f| %>
    <div>
      <%= f.fields_for :facility do |facility_fields| %>
        <div data-controller="lookup">
          <div>
            <%= facility_fields.label :name, "動物園の名前", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :name,
                  placeholder: "例：東武動物公園",
                  class: "bg-amber-700 mt-2 mb-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "name", action: "input->lookup#fetch" } %>
          </div>

          <div>
            <%= facility_fields.label :official_url, "動物園のURL", class: "text-white text-sm md:text-base" %>
            <%= facility_fields.text_field :official_url,
                  class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
                  data: { lookup_target: "url" } %>
          </div>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :image, "画像をアップロード", class: "text-white text-sm md:text-base" %>
      <%= f.file_field :image,
            class: "bg-amber-700 mt-2 block w-full border rounded-md p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :word, "ひとこと", class: "text-white text-sm md:text-base" %>
      <%= f.text_field :word,
            placeholder: "例：キリン！！",
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <div>
      <%= f.label :body, "思い出・ここが好き", class: "text-white text-sm md:text-base" %>
      <%= f.text_area :body,
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg",
            rows: "10" %>
    </div>

    <div>
      <%= f.label :area_id, "都道府県", class: "text-white text-sm md:text-base" %>
      <%= f.select :area_id, Area.all.collect { |p| [p.name, p.id] },
            { include_blank: "選択してください" },
            class: "bg-amber-700 mt-2 block w-full border rounded-md shadow-sm p-4 md:p-3 text-base md:text-lg" %>
    </div>

    <%= hidden_field_tag :category, "zoo" %>

    <div>
      <%= f.submit "投稿",
            class: "mb-12 block w-full md:w-auto bg-neutral-300 hover:bg-neutral-500 py-3 md:py-2 px-4 rounded-md shadow-md transition duration-300 text-base md:text-lg" %>
    </div>
  <% end %>
</div>

app/views/posts/zoo_show.html.erb
<%= render "shared/zoo_header" %>
<div class = "flex items-center justify-center bg-lime-900 min-h-screen">
    <div class="w-full max-w-6xl px-2 my-16">
        <div class="bg-amber-700 border rounded-lg shadow-md p-4">
            <div class="font-bold text-xl">
                <%= @post.user.name %>
            </div>
            <div class="mt-10 mb-4 font-bold text-xl">
                <%= @post.facility.name %> （ <%= @post.area.name %> ）
            </div>
            <div class="">
                <% if @post.image.attached? %>
                    <%= image_tag @post.image %>
                <% else %>
                    <%= image_tag "kirin.png", class: "" %>
                <% end %>
            </div>
            <p class = "text-center mt-12 text-xl">「 思い出・ここが好き 」</p>
            <div class= "mb-8 mt-10 rounded-lg p-8 border bg-lime-900 text-xl text-center text-white"> 
                「 <%= @post.body %> 」 
            </div>
            <p class = "text-center mt-12 text-xl">「 動物園URL 」</p>
            <div class= "underline mt-10 rounded-lg p-8 border bg-lime-900 text-xl text-white text-center"> 
                <%= link_to @post.facility.official_url,
                            @post.facility.official_url,
                            target: "_blank",
                            rel: "noopener noreferrer",
                            class: "break-all",
                            data: {
                                controller: "click-track",
                                action: "click->click-track#track",     
                                click_track_url_value: track_official_click_post_path(@post)
                            } %> 
            </div>
            <%= render partial: "likes/like_button", locals: { post: @post } %>
        </div>
            <%# 投稿したユーザーだけが編集・投稿できる　　%>
            <% if user_signed_in? && current_user.id == @post.user_id %>
                <div class="flex justify-center items-center mt-8 text-xl text-white space-x-12">
                    <%= link_to edit_post_path(category: "zoo"), class: "" do %>
                        <i class="fa-solid fa-pen-to-square text-2xl"></i>
                    <% end %>
                    <%= link_to post_path(@post), method: :delete, data: { turbo_method: :delete }, class: "" do %>
                        <i class="fa-solid fa-trash text-2xl"></i>
                    <% end %>
                </div>

            <% end %>
            <%# ライン共有ボタン %>
            <div class="line-share-button mt-8 flex justify-center items-center">
                <div class="line-it-button" 
                    data-lang="ja" 
                    data-type="share-a" 
                    data-env="REAL"
                    data-url="<%= post_url(@post, category: "zoo") %>" 
                    data-text="<%= @post.facility.name %>" 
                    data-color="default" 
                    data-size="large" 
                    data-count="true" 
                    data-ver="3" 
                    style="display: none;">
                </div>
            </div>

            <%# xのシェア機能 %>
<div class="mt-8 flex justify-center items-center">
   <% share_url = "https://twitter.com/intent/tweet?url=#{CGI.escape(request.original_url)}&text=#{CGI.escape(title)}" %>

<%= link_to share_url, target: "_blank", rel: "noopener noreferrer", class: "bg-sky-500 inline-block text-white px-4 py-2 rounded-lg" do %>
Xでシェア
<% end %>
</div>


    </div>
</div>